version: '3.8'
services:
  api:
#    container_name: mufti-belajar
    build:
#      context: mufti-belajar
      context: .
      dockerfile: Dockerfile
#    image: "mufti-belajar.jar"
    ports:
      - "8080:8080"
    depends_on:
      - c
#        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresku:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_SHOW-SQL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  postgresku:
    image: postgres:12
#    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5